site_name: Lens Documentation
site_description: Documentation for Lens IDE. The only system youâ€™ll ever need to take control of your Kubernetes clusters. It's open source and free. Download it today!
site_author: Mirantis, Inc.
site_url: https://docs.k8slens.dev
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/lensapp/lens
copyright: Copyright &copy; 2020 <a href="https://mirantis.com/">Mirantis Inc.</a> - All rights reserved.
edit_uri: ""
nav:
  - Overview: README.md
  - Getting Started: getting-started/README.md
  - Managing Clusters:
    - Adding clusters: clusters/adding-clusters.md
    - Removing cluster: clusters/removing-clusters.md
    - Settings: clusters/settings.md
  - Using Helm Charts: helm/README.md
  - Using Extensions: extensions/usage/README.md
  - Preferences: getting-started/preferences.md
  - Extension Development:
    - Overview: extensions/README.md
    - Get Started:
      - Your First Extension: extensions/get-started/your-first-extension.md
      - Extension Anatomy: extensions/get-started/anatomy.md
      - Wrapping Up: extensions/get-started/wrapping-up.md
    - Extension Capabilities:
      - Overview: extensions/capabilities/README.md
      - Common Capabilities: extensions/capabilities/common-capabilities.md
      - Styling: extensions/capabilities/styling.md
      - Color reference: extensions/capabilities/color-reference.md
    - Extension Guides:
      - Overview: extensions/guides/README.md
      - Renderer Extension: extensions/guides/renderer-extension.md
    - Testing and Publishing:
      - Testing Extensions: extensions/testing-and-publishing/testing.md
      - Publishing Extensions: extensions/testing-and-publishing/publishing.md
      - Bundling Extensions: extensions/testing-and-publishing/bundling.md
    - API Reference: extensions/api/modules/_src_extensions_extension_api_.md
  - Contributing:
    - Overview: contributing/README.md
    - Development: contributing/development.md
    - Documentation: contributing/documentation.md
    - Maintainers: contributing/maintainers.md
    - Promotion: contributing/promotion.md

  - FAQ: faq/README.md
theme:
  name: 'material'
  highlightjs: true
  language: 'en'
  custom_dir: docs/custom_theme
  favicon: img/favicon.ico
  logo: img/lens-logo-icon.svg
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - navigation.instant
    - toc.autohide
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - pymdownx.highlight: {}
  - pymdownx.superfences: {}
  - pymdownx.inlinehilite: {}
  - toc:
      permalink: "#"
      toc_depth: 3

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lensapp/lens
      name: Lens on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/k8slens
      name: Lens on Twitter
    - icon: fontawesome/brands/slack
      link: http://k8slens.slack.com/
      name: Lens on Slack
    - icon: fontawesome/solid/link
      link: https://k8slens.dev/
      name: Lens Website
  version:
    method: mike
