name: Publish NPM Package `master`
on:
  pull_request:
    types:
      - closed
concurrency:
  group: publish-master-npm
  cancel-in-progress: true
jobs:
  publish:
    name: Publish Extensions NPM Package `master`
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'area/extension') }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Release
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate NPM package
        run: |
          make build-extensions-npm

      - name: publish new release
        run: |
          make publish-extensions-npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_RELEASE_TAG: master
