name: Release Open Lens
on:
  pull_request:
    types:
      - closed
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Print event
        run: |
          echo "merged=${{ github.event.pull_request.merged }}"
          echo "ref=${{ github.event.pull_request.base.ref }}"
          echo "targets_master=${{ github.event.pull_request.base.ref == 'master' }}"
          echo "targets_release_branch=${{ startsWith(github.event.pull_request.base.ref, 'release/v') }}"
          echo "is_release=${{ contains(github.event.pull_request.labels.*.name, 'release') }}"
          echo "should_continue_release=${{ true && true && (false || true) }}"
          echo "should_continue=${{ github.event.pull_request.merged == 'true' && contains(github.event.pull_request.labels.*.name, 'release') && (github.event.pull_request.base.ref == 'master' || startsWith(github.event.pull_request.base.ref, 'release/v')) }}"
          exit 1
      # - name: Checkout Release from lens
      #   uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      # - uses: butlerlogic/action-autotag@stable
      #   id: tagger
      #   with:
      #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      #     tag_prefix: "v"
      # - uses: ncipollo/release-action@v1
      #   if: ${{ needs.tag.outputs.tagname != '' }}
      #   with:
      #     name: v${{ steps.open-lens-version.outputs.VERSION }}
      #     commit: master
      #     tag: v${{ steps.open-lens-version.outputs.VERSION }}
      #     body: ${{ github.event.pull_request.body }}
